version: "3.9"
networks: { public: {}, internal: {} }
services:
  traefik:
    image: traefik:v3.0
    command: [ "--api.dashboard=false", "--providers.docker=true", "--providers.docker.exposedbydefault=false", "--entrypoints.web.address=:80" ]
    ports: [ "80:80" ]
    volumes: [ "/var/run/docker.sock:/var/run/docker.sock:ro" ]
    networks: [ public ]
  n8n-main:
    image: docker.n8n.io/n8nio/n8n:latest
    env_file: .env
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${POSTGRES_HOST}
      DB_POSTGRESDB_PORT: ${POSTGRES_PORT}
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: ${REDIS_HOST}
      QUEUE_BULL_REDIS_PORT: ${REDIS_PORT}
      QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_LOG_LEVEL: info
      N8N_EDITOR_BASE_URL: ${WEBHOOK_URL}
      WEBHOOK_URL: ${WEBHOOK_URL}
    networks: [ internal, public ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`n8n.${PUBLIC_DOMAIN}`)"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"
  n8n-worker:
    image: docker.n8n.io/n8nio/n8n:latest
    env_file: .env
    command: [ "n8n","worker" ]
    environment:
      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: ${POSTGRES_HOST}
      DB_POSTGRESDB_PORT: ${POSTGRES_PORT}
      DB_POSTGRESDB_DATABASE: ${POSTGRES_DB}
      DB_POSTGRESDB_USER: ${POSTGRES_USER}
      DB_POSTGRESDB_PASSWORD: ${POSTGRES_PASSWORD}
      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: ${REDIS_HOST}
      QUEUE_BULL_REDIS_PORT: ${REDIS_PORT}
      QUEUE_BULL_REDIS_PASSWORD: ${REDIS_PASSWORD}
      N8N_ENCRYPTION_KEY: ${N8N_ENCRYPTION_KEY}
      N8N_LOG_LEVEL: info
    networks: [ internal ]
  langgraph-api:
    image: ghcr.io/youruser/leverage-langgraph:latest
    env_file: .env
    environment:
      S3_ENDPOINT: ${S3_ENDPOINT}
      S3_ACCESS_KEY: ${S3_ACCESS_KEY}
      S3_SECRET_KEY: ${S3_SECRET_KEY}
      S3_BUCKET: ${S3_BUCKET}
      S3_USE_SSL: ${S3_USE_SSL}
      QDRANT_HOST: ${QDRANT_HOST}
      QDRANT_PORT: ${QDRANT_PORT}
    networks: [ internal, public ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.${PUBLIC_DOMAIN}`)"
      - "traefik.http.services.api.loadbalancer.server.port=8000"
